services:
  admin-web:
    build: src
    container_name: admin-web
    restart: unless-stopped
    ports:
      - "8080:80" # 假设你的前端应用在容器内运行在80端口，映射到宿主机的8080
    environment:
      # 这是最重要的部分！告诉前端应用，API的地址是 node-api 这个主机名的3000端口
      - .env.production # 指定环境变量文件的路径
    depends_on:
      - admin-api # 可选：声明依赖，启动前端前先启动后端（但不会等待后端“健康”）
    networks:
      - admin-network # 接入同一个自定义网络！

# 关键：这里不是重新创建网络，而是引用步骤一中已存在的同名网络
networks:
  admin-network:
    external: true # 声明这是一个外部已存在的网络
    name: admin-network # 指定网络的确切名称
